"""
Configuration constants for the simulation.
"""

# Agent Stats
MAX_STAT_VALUE = 10
HUNGER_THRESHOLD_LOW = 5
ENERGY_THRESHOLD_LOW = 5

# Resource Balancing
DEFAULT_BERRY_MAX = 1
DEFAULT_BERRY_REGEN = 1
DEFAULT_BERRY_YIELD = 1
DEFAULT_BERRY_HUNGER = 4

# Simulation Intervals
DEFAULT_TICK_INTERVAL = 5
MEMORY_WINDOW_LIMIT = 20
CHRONICLE_LIMIT = 30

# Energy Gains
ENERGY_GAIN_SHELTER = 5
ENERGY_GAIN_ANYWHERE = 2
